package com.wemingle.core.domain.report.entity.reportitem;

public enum ReportItem {
    DEFAMATION_AND_PROFANITY, PRIVACY_INVASION, INAPPROPRIATE_ADVERTISING_AND_VIRAL_MARKETING, PORNOGRAPHIC_CONTENT, IMPERSONATION_AND_FRAUD, MISCONDUCT_OR_UNCIVIL_BEHAVIOR
}
