##common setting
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: wemingleteam@gmail.com
    password: ENC(O/Aw9bvHjfnoXTLIpVGUSqstDMU1G4mEq9oyeC/R4pY=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        protocol: smtp
    test-connection: true
---
## prod setting
spring:
  profiles:
    active: prod

jasypt:
  encryptor:
    bean: jasyptEncryptor
    
---
## jungwooLocal
spring:
  profiles:
    active: jungwoo

  datasource:
    url: ENC(OWM8GJAYIIZBILEDUOrxp/+SXrUu6cTBAECgWoohRDuXsSFNhvCQ23Cj8hzgpeK4oTqnsGOyEuTyPTU8b7ES2qgSnYtIK14Lbnk/Q63cCqvmlwAp2vRhwR2mcbAs1hPx)
    username: ENC(ApmdwaV15BRKLL0WmZV9QA==)
    password: ENC(nN/GHvgyZLbz7vhsaYBagTczwxNBREOi)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

---

## howangLocal
spring:
  profiles:
    active: howang

  datasource:
    url: ENC(OWM8GJAYIIZBILEDUOrxp/+SXrUu6cTBAECgWoohRDuXsSFNhvCQ23Cj8hzgpeK4oTqnsGOyEuTyPTU8b7ES2qgSnYtIK14Lbnk/Q63cCqvmlwAp2vRhwR2mcbAs1hPx)
    username: ENC(ApmdwaV15BRKLL0WmZV9QA==)
    password: ENC(nN/GHvgyZLbz7vhsaYBagTczwxNBREOi)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect



