#JWT
jwt:
  issuer: thrusum123@gmail.com
  secret_key: ENC(GEvBTNbOBf8K0wL2KtWDdGD7+Pqpk9ck6uDFl1sIIlsVY0wNlcWrgxtNICCHrdAx/M+WiesQrOXdPfdQR2jC5TKBQoHG13i05CSF+uoL3H5Yk/v6buGKaBBBqM9AmQA6CBGsiq9ejQ2PR+Cdi09TRJo003DeJXeflkF5xhJ+vHHOgfLR7F3c2FW3Z610wI6m)

#JASYPT
jasypt:
  encryptor:
    bean: jasyptEncryptor

##common setting
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: wemingleteam@gmail.com
    password: ENC(O/Aw9bvHjfnoXTLIpVGUSqstDMU1G4mEq9oyeC/R4pY=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        protocol: smtp
    test-connection: true

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
---
## prod setting
spring:
  profiles:
    active: prod

---

## jungwooLocal
spring:
  profiles:
    active: jungwoo

  datasource:
    url: ENC(OWM8GJAYIIZBILEDUOrxp/+SXrUu6cTBAECgWoohRDuXsSFNhvCQ23Cj8hzgpeK4oTqnsGOyEuTyPTU8b7ES2qgSnYtIK14Lbnk/Q63cCqvmlwAp2vRhwR2mcbAs1hPx)
    username: ENC(ApmdwaV15BRKLL0WmZV9QA==)
    password: ENC(nN/GHvgyZLbz7vhsaYBagTczwxNBREOi)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

---

## howangLocal
spring:
  profiles:
    active: howang

  datasource:
    url: ENC(OWM8GJAYIIZBILEDUOrxp/+SXrUu6cTBAECgWoohRDuXsSFNhvCQ23Cj8hzgpeK4oTqnsGOyEuTyPTU8b7ES2qgSnYtIK14Lbnk/Q63cCqvmlwAp2vRhwR2mcbAs1hPx)
    username: ENC(ApmdwaV15BRKLL0WmZV9QA==)
    password: ENC(nN/GHvgyZLbz7vhsaYBagTczwxNBREOi)
    driver-class-name: com.mysql.cj.jdbc.Driver